version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo apt-get update && sudo apt-get install -y cmake
      - run:
          name: Build and simulate FMUs
          command: python test_build.py
